project:
  type: website
  post-render:
    - "cp -rn static/. _site/"
    - "cp assets/img/left.png _site/assets/img/"
    - "cp assets/img/middle.png _site/assets/img/"
    - "cp assets/img/right.png _site/assets/img/"

execute:
  freeze: auto

website:
  title: "Data Imaginist"
  site-url: "https://data-imaginist.com"
  navbar:
    logo: assets/img/logo_small.png
    right:
      - text: Main Packages
        menu:
          - text: gganimate
            href: https://gganimate.com
          - text: patchwork
            href: https://patchwork.data-imaginist.com
          - text: ggraph
            href: https://ggraph.data-imaginist.com
          - text: tidygraph
            href: https://tidygraph.data-imaginist.com
          - text: ggforce
            href: https://ggforce.data-imaginist.com
          - text: ggfx
            href: https://ggfx.data-imaginist.com
          - text: euclid
            href: https://r-euclid.com
      - text: Art
        menu:
          - text: Prints
            file: art/index.qmd
          - text: NFTs
            file: nft/index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/thomasp85
      - icon: twitter
        href: https://twitter.com/thomasp85
  page-footer: "Copyright 2023, Thomas Lin Pedersen"
  twitter-card: true
  open-graph: true

format:
  html:
    theme:
      - minty
      - custom.scss

editor: visual

highlight-style: "zenburn"
